// src/components/integrations/Integrations.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  type ToastVariant = 'success' | 'error' | 'warning';

  type IntegrationToast = {
    id: number;
    variant: ToastVariant;
    message: string;
    visible: boolean;
  };

  type IntegrationsClientState = {
    isInitialLoading: boolean;
    showSticky: boolean;
    sessionPending: boolean;
    isSignedIn: boolean;
    signupHref: string;
    fullName: string;
    memberId: string;
    displayFullName: string;
    isSaving: boolean;
    isGeneratingPass: boolean;
    isGeneratingGooglePass: boolean;
    calendarId: string;
    isCalendarModalOpen: boolean;
    calendarDisplayUrl: string;
    googleCalendarUrl: string;
    outlookCalendarUrl: string;
    selectedJobs: string[];
    jobSearch: string;
    isJobDropdownOpen: boolean;
    highlightedJobIndex: number;
    filteredJobOptions: string[];
    pushSupported: boolean;
    canManageNotifications: boolean;
    pushEnabled: boolean;
    pushLoading: boolean;
    isSendingTest: boolean;
    toasts: IntegrationToast[];
    onMemberNameChange: (value: string) => void;
    onMemberIdChange: (value: string) => void;
    onSave: () => Promise<void>;
    onAddToWallet: () => Promise<void>;
    onAddToGoogleWallet: () => Promise<void>;
    onOpenCalendarModal: () => void;
    onCloseCalendarModal: () => void;
    onCopyCalendarUrl: () => Promise<void>;
    onJobSearchChange: (value: string) => void;
    onJobSearchFocus: () => void;
    onJobSearchBlur: () => void;
    onJobSearchKeyDown: (event: KeyboardEvent) => void;
    onToggleJob: (job: string) => void;
    onRemoveJob: (job: string) => void;
    onHighlightJobIndex: (index: number) => void;
    onTogglePush: () => Promise<void>;
    onSendTestNotification: () => Promise<void>;
  };

  let {
    channel,
    initialState,
  }: {
    channel: string;
    initialState: IntegrationsClientState;
  } = $props();

  let isInitialLoading = $state(true);
  let showSticky = $state(true);
  let sessionPending = $state(true);
  let isSignedIn = $state(false);
  let signupHref = $state('/signup?next=%2Fintegrations');
  let fullName = $state('');
  let memberId = $state('');
  let displayFullName = $state('');
  let isSaving = $state(false);
  let isGeneratingPass = $state(false);
  let isGeneratingGooglePass = $state(false);
  let calendarId = $state('');
  let isCalendarModalOpen = $state(false);
  let googleCalendarUrl = $state('');
  let outlookCalendarUrl = $state('');
  let selectedJobs = $state<string[]>([]);
  let jobSearch = $state('');
  let isJobDropdownOpen = $state(false);
  let highlightedJobIndex = $state(0);
  let filteredJobOptions = $state<string[]>([]);
  let pushSupported = $state(false);
  let canManageNotifications = $state(false);
  let pushEnabled = $state(false);
  let pushLoading = $state(false);
  let isSendingTest = $state(false);
  let toasts = $state<IntegrationToast[]>([]);

  let onMemberNameChange = $state<(value: string) => void>(() : void => {});
  let onMemberIdChange = $state<(value: string) => void>(() : void => {});
  let onSave = $state<() => Promise<void>>(async () : Promise<void> => {});
  let onAddToWallet = $state<() => Promise<void>>(async () : Promise<void> => {});
  let onAddToGoogleWallet = $state<() => Promise<void>>(async () : Promise<void> => {});
  let onOpenCalendarModal = $state<() => void>(() : void => {});
  let onCloseCalendarModal = $state<() => void>(() : void => {});
  let onCopyCalendarUrl = $state<() => Promise<void>>(async () : Promise<void> => {});
  let onJobSearchChange = $state<(value: string) => void>(() : void => {});
  let onJobSearchFocus = $state<() => void>(() : void => {});
  let onJobSearchBlur = $state<() => void>(() : void => {});
  let onJobSearchKeyDown = $state<(event: KeyboardEvent) => void>(() : void => {});
  let onToggleJob = $state<(job: string) => void>(() : void => {});
  let onRemoveJob = $state<(job: string) => void>(() : void => {});
  let onHighlightJobIndex = $state<(index: number) => void>(() : void => {});
  let onTogglePush = $state<() => Promise<void>>(async () : Promise<void> => {});
  let onSendTestNotification = $state<() => Promise<void>>(async () : Promise<void> => {});

  let headerRef = $state<HTMLDivElement | null>(null);
  let cardRef = $state<HTMLDivElement | null>(null);
  let shineRef = $state<HTMLDivElement | null>(null);

  function applyState(next: IntegrationsClientState) : void {
    isInitialLoading = next.isInitialLoading;
    showSticky = next.showSticky;
    sessionPending = next.sessionPending;
    isSignedIn = next.isSignedIn;
    signupHref = next.signupHref;
    fullName = next.fullName;
    memberId = next.memberId;
    displayFullName = next.displayFullName;
    isSaving = next.isSaving;
    isGeneratingPass = next.isGeneratingPass;
    isGeneratingGooglePass = next.isGeneratingGooglePass;
    calendarId = next.calendarId;
    isCalendarModalOpen = next.isCalendarModalOpen;
    googleCalendarUrl = next.googleCalendarUrl;
    outlookCalendarUrl = next.outlookCalendarUrl;
    selectedJobs = next.selectedJobs;
    jobSearch = next.jobSearch;
    isJobDropdownOpen = next.isJobDropdownOpen;
    highlightedJobIndex = next.highlightedJobIndex;
    filteredJobOptions = next.filteredJobOptions;
    pushSupported = next.pushSupported;
    canManageNotifications = next.canManageNotifications;
    pushEnabled = next.pushEnabled;
    pushLoading = next.pushLoading;
    isSendingTest = next.isSendingTest;
    toasts = next.toasts;

    onMemberNameChange = next.onMemberNameChange;
    onMemberIdChange = next.onMemberIdChange;
    onSave = next.onSave;
    onAddToWallet = next.onAddToWallet;
    onAddToGoogleWallet = next.onAddToGoogleWallet;
    onOpenCalendarModal = next.onOpenCalendarModal;
    onCloseCalendarModal = next.onCloseCalendarModal;
    onCopyCalendarUrl = next.onCopyCalendarUrl;
    onJobSearchChange = next.onJobSearchChange;
    onJobSearchFocus = next.onJobSearchFocus;
    onJobSearchBlur = next.onJobSearchBlur;
    onJobSearchKeyDown = next.onJobSearchKeyDown;
    onToggleJob = next.onToggleJob;
    onRemoveJob = next.onRemoveJob;
    onHighlightJobIndex = next.onHighlightJobIndex;
    onTogglePush = next.onTogglePush;
    onSendTestNotification = next.onSendTestNotification;
  }

  function handleStateUpdate(event: Event) : void {
    if (!(event instanceof CustomEvent)) {return;}
    applyState(event.detail as IntegrationsClientState);
  }

  function handleCardMouseMove(event: MouseEvent) : void {
    const target = event.currentTarget as HTMLDivElement;
    const rect = target.getBoundingClientRect();
    const x = event.clientX - rect.left;
    const y = event.clientY - rect.top;
    const centerX = rect.width / 2;
    const centerY = rect.height / 2;
    const rotateX = ((y - centerY) / centerY) * -8;
    const rotateY = ((x - centerX) / centerX) * 8;

    target.style.transform = `rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;

    if (shineRef) {
      shineRef.style.opacity = '1';
      shineRef.style.background = `radial-gradient(circle at ${x}px ${y}px, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0) 50%)`;
    }
  }

  function handleCardMouseLeave(event: MouseEvent) : void {
    const target = event.currentTarget as HTMLDivElement;
    target.style.transform = 'rotateX(0deg) rotateY(0deg)';
    if (shineRef) {
      shineRef.style.opacity = '0';
    }
  }

  onMount(() : () => void => {
    applyState(initialState);

    const handler = (event: Event) : void => handleStateUpdate(event);
    window.addEventListener(`integrations-state:update:${channel}`, handler as EventListener);

    return () : void => {
      window.removeEventListener(`integrations-state:update:${channel}`, handler as EventListener);
    };
  });

  $effect(() : (() => void) | undefined => {
    const element = headerRef;
    if (!element || typeof ResizeObserver === 'undefined') {
      return;
    }

    const updateHeight = () : void => {
      window.dispatchEvent(new CustomEvent('sticky-threshold', { detail: element.offsetHeight }));
    };

    updateHeight();
    const observer = new ResizeObserver(updateHeight);
    observer.observe(element);

    return () : void => observer.disconnect();
  });
</script>

<div>
  <div
    bind:this={headerRef}
    class={`sticky top-[5.5rem] z-20 bg-white transition-opacity duration-300 ease-in-out motion-reduce:transition-none ${showSticky ? 'opacity-100' : 'pointer-events-none opacity-0'}`}
  >
    <h1 class="mx-auto max-w-3xl px-4 pt-6 pb-6 text-2xl font-bold text-zinc-900">Integrations</h1>
  </div>

  <div class="mx-auto max-w-3xl px-4 pb-6">
    {#if isInitialLoading}
      <div class="animate-pulse">
        <div class="mb-6 h-8 w-32 rounded bg-zinc-200"></div>
        <div class="space-y-4">
          <div class="h-10 rounded bg-zinc-200"></div>
          <div class="h-10 rounded bg-zinc-200"></div>
        </div>
      </div>
    {:else}
      {#if !isSignedIn && !sessionPending}
        <div class="mb-6 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
          <a href={signupHref} class="font-semibold underline underline-offset-4">Create an account</a>
          to save changes, add wallet passes, and subscribe to the shift calendar.
        </div>
      {/if}

      <form
        onsubmit={(event) => {
          event.preventDefault();
          void onSave();
        }}
        class="space-y-6"
      >
        <section class="space-y-4">
          <h2 class="text-lg font-semibold text-zinc-900">Profile</h2>
          <p class="mt-2 text-sm text-zinc-600">Edit your unofficial member card.</p>

          <div class="w-full max-w-sm" style="perspective: 1000px;">
            <div
              bind:this={cardRef}
              class="relative aspect-[1.586/1] w-full overflow-hidden rounded-2xl shadow-xl transition-transform duration-300 ease-out hover:shadow-2xl"
              style="background-color: rgb(255, 246, 220); background-image: url('/assets/coop-strip.png'); background-position: center 12%; background-repeat: no-repeat; background-size: 20% auto; transform-style: preserve-3d;"
              role="img"
              aria-label="Apple Wallet member card preview"
              onmousemove={handleCardMouseMove}
              onmouseleave={handleCardMouseLeave}
            >
              <div bind:this={shineRef} class="pointer-events-none absolute inset-0 transition-opacity duration-300" style="opacity: 0;"></div>

              <div class="absolute top-4 right-4 left-4 flex items-start justify-between">
                <div class="flex items-center gap-2">
                  <img src="/assets/coop-padded.png" alt="Park Slope Food Coop" class="h-7 w-auto" />
                </div>
              </div>

              <div class="absolute top-1/3 right-4 left-4">
                <label for="cardMemberName" class="block text-[10px] tracking-wider uppercase" style="color: rgba(51, 51, 51, 0.6);">
                  MEMBER
                </label>
                <div class="group relative">
                  <input
                    type="text"
                    id="cardMemberName"
                    value={displayFullName}
                    oninput={(event) => onMemberNameChange((event.currentTarget as HTMLInputElement).value)}
                    placeholder="Your Name"
                    class="w-full rounded-t border-b border-dashed bg-transparent px-1 py-0.5 text-xl font-semibold transition-colors placeholder:text-zinc-400 focus:outline-none"
                    style="color: rgb(51, 51, 51); border-color: rgba(51, 51, 51, 0.35);"
                  />
                  <svg
                    class="pointer-events-none absolute top-1/2 right-1 h-4 w-4 -translate-y-1/2 transition-colors"
                    style="color: rgba(51, 51, 51, 0.35);"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    aria-hidden="true"
                    focusable="false"
                  >
                    <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"></path>
                    <path d="m15 5 4 4"></path>
                  </svg>
                </div>
              </div>

              <div class="absolute right-4 bottom-[18%] left-4">
                <label for="cardMemberId" class="block text-[10px] tracking-wider uppercase" style="color: rgba(51, 51, 51, 0.6);">
                  MEMBER ID
                </label>
                <div class="group relative w-fit">
                  <input
                    type="text"
                    id="cardMemberId"
                    inputmode="numeric"
                    value={memberId}
                    oninput={(event) => onMemberIdChange((event.currentTarget as HTMLInputElement).value)}
                    placeholder="000000"
                    class="w-32 rounded-t border-b border-dashed bg-transparent px-1 py-0.5 text-xl font-semibold transition-colors placeholder:text-zinc-400 focus:outline-none"
                    style="color: rgb(51, 51, 51); border-color: rgba(51, 51, 51, 0.35);"
                  />
                  <svg
                    class="pointer-events-none absolute top-1/2 right-1 h-4 w-4 -translate-y-1/2 transition-colors"
                    style="color: rgba(51, 51, 51, 0.35);"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    aria-hidden="true"
                    focusable="false"
                  >
                    <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"></path>
                    <path d="m15 5 4 4"></path>
                  </svg>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div class="flex gap-2">
          <button
            type="submit"
            disabled={isSaving}
            class="rounded-lg bg-black px-4 py-1.5 text-sm font-medium text-white transition-colors hover:bg-zinc-800 disabled:bg-zinc-400 disabled:opacity-60"
          >
            {isSaving ? 'Saving...' : 'Save'}
          </button>
          <button
            type="button"
            onclick={() => void onAddToWallet()}
            disabled={isGeneratingPass || !memberId || !displayFullName}
            class="transition-opacity hover:opacity-80 disabled:opacity-40"
          >
            <img src="/apple-wallet.svg" alt="Add to Apple Wallet" class="h-[34px]" />
          </button>
          <button
            type="button"
            onclick={() => void onAddToGoogleWallet()}
            disabled={isGeneratingGooglePass || !memberId || !displayFullName}
            class="transition-opacity hover:opacity-80 disabled:opacity-40"
          >
            <img src="/google-wallet.svg" alt="Add to Google Wallet" class="h-[34px]" />
          </button>
        </div>
      </form>

      <section class="mt-10">
        <h2 class="text-lg font-semibold text-zinc-900">Calendar</h2>
        <p class="mt-2 text-sm text-zinc-600">
          Link your account to your calendar to view your prospective shifts.
        </p>

        <div class="mt-6 rounded-xl border border-zinc-200 bg-white p-4">
          <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h3 class="text-base font-semibold text-zinc-900">Shift Calendar Syncing</h3>
              <p class="mt-1 text-sm text-zinc-600">
                Sync the shift calendar with your Google, Outlook, or Apple calendar.
              </p>
            </div>
            <button
              type="button"
              onclick={onOpenCalendarModal}
              class="rounded-xl bg-black px-4 py-2 font-medium text-white transition-colors hover:bg-zinc-800"
            >
              Add iCal subscription
            </button>
          </div>

          <div class="mt-6 space-y-3">
            <div class="space-y-1">
              <h3 class="text-base font-semibold text-zinc-900">Selected Shifts</h3>
              <p class="text-sm text-zinc-600">Filter the shift calendar for your preferred shifts.</p>
            </div>
            <div class="relative">
              <input
                type="text"
                value={jobSearch}
                oninput={(event) =>
                  onJobSearchChange((event.currentTarget as HTMLInputElement).value)}
                onfocus={onJobSearchFocus}
                onblur={onJobSearchBlur}
                onkeydown={(event) => onJobSearchKeyDown(event)}
                placeholder="Search jobs"
                class="w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm text-zinc-900 shadow-sm focus:ring-2 focus:ring-green-500 focus:outline-none"
              />
              {#if isJobDropdownOpen}
                <div class="absolute z-10 mt-2 w-full rounded-xl border border-zinc-200 bg-white shadow-lg">
                  <div class="max-h-48 overflow-y-auto">
                    {#if filteredJobOptions.length > 0}
                      {#each filteredJobOptions as job, index (job)}
                        {@const isSelected = selectedJobs.includes(job)}
                        {@const isHighlighted = index === highlightedJobIndex}
                        <button
                          type="button"
                          onclick={() => onToggleJob(job)}
                          onmouseenter={() => onHighlightJobIndex(index)}
                          class={`flex w-full items-center justify-between px-3 py-2 text-left text-sm transition-colors ${
                            isSelected ? 'bg-green-50 text-green-700' : 'text-zinc-700 hover:bg-zinc-100'
                          } ${isHighlighted && !isSelected ? 'bg-zinc-100' : ''}`}
                        >
                          <span>{job}</span>
                          {#if isSelected}
                            <span class="text-xs">Selected</span>
                          {/if}
                        </button>
                      {/each}
                    {:else}
                      <div class="px-3 py-2 text-sm text-zinc-500">No matching jobs.</div>
                    {/if}
                  </div>
                </div>
              {/if}
            </div>

            <div class="flex flex-wrap gap-2">
              {#if selectedJobs.length > 0}
                {#each selectedJobs as job (job)}
                  <span
                    class="group inline-flex items-center gap-2 rounded-full bg-zinc-100 px-3 py-1 text-xs font-medium text-zinc-700 transition-colors hover:bg-red-50 hover:text-red-700"
                  >
                    {job}
                    <button
                      type="button"
                      onclick={() => onRemoveJob(job)}
                      class="text-xs font-semibold text-zinc-400 transition-colors group-hover:text-red-600"
                      aria-label={`Remove ${job}`}
                    >
                      ×
                    </button>
                  </span>
                {/each}
              {:else}
                <span class="text-sm text-zinc-500">All shifts included.</span>
              {/if}
            </div>
          </div>
        </div>
      </section>

      {#if pushSupported && canManageNotifications}
        <section class="mt-10">
          <h2 class="text-lg font-semibold text-zinc-900">Notifications</h2>
          <p class="mt-2 text-sm text-zinc-600">Receive push notifications from foodcoop.news.</p>

          <div class="mt-6 rounded-xl border border-zinc-200 bg-white p-4">
            <div class="flex items-center justify-between">
              <div>
                <h3 class="text-base font-semibold text-zinc-900">Push Notifications</h3>
                <p class="mt-1 text-sm text-zinc-600">Get notified about updates and announcements.</p>
              </div>
              <button
                type="button"
                role="switch"
                aria-checked={pushEnabled}
                aria-label="Toggle push notifications"
                disabled={pushLoading}
                onclick={() => void onTogglePush()}
                class={`relative inline-flex h-7 w-12 shrink-0 cursor-pointer items-center rounded-full transition-colors duration-200 ease-in-out disabled:opacity-50 ${
                  pushEnabled ? 'bg-green-600' : 'bg-zinc-300'
                }`}
              >
                <span
                  class={`inline-block h-5 w-5 rounded-full bg-white shadow-sm transition-transform duration-200 ease-in-out ${
                    pushEnabled ? 'translate-x-6' : 'translate-x-1'
                  }`}
                ></span>
              </button>
            </div>

            {#if pushEnabled}
              <div class="mt-4 border-t border-zinc-100 pt-4">
                <button
                  type="button"
                  onclick={() => void onSendTestNotification()}
                  disabled={isSendingTest}
                  class="rounded-xl bg-green-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-green-700 disabled:bg-green-400 disabled:opacity-60"
                >
                  {isSendingTest ? 'Sending...' : 'Send test notification'}
                </button>
              </div>
            {/if}
          </div>
        </section>
      {/if}

    {/if}
  </div>

  {#if isCalendarModalOpen}
    <div class="fixed inset-0 z-50 flex items-center justify-center px-4">
      <button
        type="button"
        aria-label="Close calendar modal"
        onclick={onCloseCalendarModal}
        class="absolute inset-0 bg-black/40"
      ></button>
      <div class="relative w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl">
        <div>
          <h3 class="text-lg font-semibold text-zinc-900">📅 Add iCal subscription</h3>
          <p class="mt-2 text-sm text-zinc-600">
            Add the shift calendar to your calendar app to keep up with new shifts and updates.
          </p>
        </div>

        <div class="mt-6 space-y-3">
          <a
            href={googleCalendarUrl}
            target="_blank"
            rel="noreferrer"
            class="block w-full rounded-xl bg-[#0b57d0] px-4 py-2 text-center font-medium text-white transition-colors hover:bg-[#0842a0]"
          >
            Add to Google Calendar
          </a>
          <a
            href={outlookCalendarUrl}
            target="_blank"
            rel="noreferrer"
            class="block w-full rounded-xl bg-[#0F6CBD] px-4 py-2 text-center font-medium text-white transition-colors hover:bg-[#0c5a9e]"
          >
            Add to Outlook Calendar
          </a>
          <button
            type="button"
            onclick={() => void onCopyCalendarUrl()}
            disabled={!calendarId}
            class="w-full rounded-xl bg-zinc-100 px-4 py-2 font-medium text-zinc-500 transition-colors hover:text-zinc-700 disabled:opacity-60 disabled:hover:text-zinc-500"
          >
            Add URL to clipboard
          </button>
        </div>
      </div>
    </div>
  {/if}

  {#if toasts.length > 0}
    <div class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 space-y-2">
      {#each toasts as toast (toast.id)}
        <div
          class={`rounded-xl border border-zinc-200 bg-white px-4 py-3 text-sm font-medium shadow-lg transition-all duration-300 ease-out ${
            toast.visible ? 'translate-y-0 opacity-100' : 'translate-y-2 opacity-0'
          }`}
        >
          <span
            class={
              toast.variant === 'success'
                ? 'text-green-600'
                : toast.variant === 'warning'
                  ? 'text-amber-600'
                  : 'text-red-600'
            }
          >
            {toast.message}
          </span>
        </div>
      {/each}
    </div>
  {/if}
</div>

// src/components/Integrations.tsx
'use client';

import { useState, useEffect, useRef, CSSProperties } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useQuery, useMutation } from 'convex/react';
import { api } from '../../convex/_generated/api';
import { useSession } from '@/lib/auth-client';
import { AppleWalletCard } from './AppleWalletCard';
import { useScrollVisibility } from '@/components/ScrollVisibilityProvider';

const CALENDAR_PROXY_PATH = '/api/calendar';
const DRAFT_STORAGE_KEY = 'integrations:draft';

const SHIFT_JOB_OPTIONS = [
  '🚽 Bathroom',
  '🍺 Beer',
  '🧼 Bins',
  '🍞 Bread Stocking',
  '🫘 Bulk Lifting',
  '🛒 Cart Return',
  '🧽 Case Maintenance',
  '💵 Cashier',
  '💳 Checkout',
  '🍛 CHIPS Food Drive',
  'CHiPS Gala',
  '🏝 Cleaning',
  '🥛 Dairy Lifting',
  '🚛 Delivery Support',
  '💰 Drawer',
  '⌨️ Enrollment Data Entry',
  '📃 Enrollment',
  '🎟 Entrance/Greeter',
  '🥫 Flex',
  '🍿 Food Processing TL ',
  '🍿 Food Processing ',
  '👀 Front End Support',
  '🗳️ General Meeting',
  '🧴 Health & Beauty',
  '🖥 Inventory Data',
  '📋 Inventory',
  '🍀 Inventory: Produce',
  '🚚 Lifting',
  '🍖 Meat Processing & Lifting',
  '📗 Office',
  '🥬 Produce Processing',
  '🥦 Producer',
  '📦 Receiving: Team Leader',
  '🛠 Repairs',
  '🖨 Scan Invoices',
  '🧺 Set-up & Equipment Cleaning',
  '🗂 Sort & Collate',
  'Soup Cleaning',
  '🍲 Soup: Food Services',
  '✍️ Soup: Guest Services- Outdoor',
  '🙂 Soup: Reception',
  'Special Project: Data Entry',
  '📦 Stocking',
  '🦃 Turkey',
  '🍬 Vitamins',
  '🧾 Vouchers',
];

type ToastVariant = 'success' | 'error' | 'warning';
type IntegrationDraft = {
  fullName: string;
  memberId: string;
  selectedJobs: string[];
};

const loadDraft = (): IntegrationDraft | null => {
  if (typeof window === 'undefined') {
    return null;
  }

  try {
    const raw = window.localStorage.getItem(DRAFT_STORAGE_KEY);
    if (!raw) {
      return null;
    }

    const parsed = JSON.parse(raw) as Partial<IntegrationDraft>;
    if (!parsed || typeof parsed !== 'object') {
      return null;
    }

    const fullName = typeof parsed.fullName === 'string' ? parsed.fullName : '';
    const memberId = typeof parsed.memberId === 'string' ? parsed.memberId : '';
    const selectedJobs = Array.isArray(parsed.selectedJobs)
      ? parsed.selectedJobs.filter((job): job is string => typeof job === 'string')
      : [];

    return { fullName, memberId, selectedJobs };
  } catch {
    return null;
  }
};

const saveDraft = (draft: IntegrationDraft) => {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    window.localStorage.setItem(DRAFT_STORAGE_KEY, JSON.stringify(draft));
  } catch {
    // Ignore localStorage write errors
  }
};

const clearDraft = () => {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    window.localStorage.removeItem(DRAFT_STORAGE_KEY);
  } catch {
    // Ignore localStorage errors
  }
};

const normalizeJobSortKey = (job: string) =>
  job
    .replace(/^\p{Extended_Pictographic}+\s*/gu, '')
    .toLowerCase()
    .trim();

export function Integrations() {
  const router = useRouter();
  const { data: session, isPending: sessionPending } = useSession();
  const memberProfile = useQuery(api.memberProfiles.getMemberProfile);
  const updateMemberProfile = useMutation(api.memberProfiles.updateMemberProfile);
  const { showSticky } = useScrollVisibility();

  const [fullName, setFullName] = useState('');
  const [memberId, setMemberId] = useState('');
  const [selectedJobs, setSelectedJobs] = useState<string[]>([]);
  const [calendarId, setCalendarId] = useState('');
  const [calendarOrigin, setCalendarOrigin] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isCalendarModalOpen, setIsCalendarModalOpen] = useState(false);
  const [jobSearch, setJobSearch] = useState('');
  const [isJobDropdownOpen, setIsJobDropdownOpen] = useState(false);
  const [highlightedJobIndex, setHighlightedJobIndex] = useState(0);
  const jobOptionRefs = useRef<Record<string, HTMLButtonElement | null>>({});
  const isDraftReadyRef = useRef(false);
  const [toasts, setToasts] = useState<
    {
      id: number;
      variant: 'success' | 'error' | 'warning';
      message: string;
      visible: boolean;
    }[]
  >([]);
  const [isGeneratingPass, setIsGeneratingPass] = useState(false);
  const [isGeneratingGooglePass, setIsGeneratingGooglePass] = useState(false);
  const headerRef = useRef<HTMLDivElement>(null);
  const [headerHeight, setHeaderHeight] = useState(0);

  // Initialize form with profile data
  useEffect(() => {
    const sortJobs = (jobs: string[]) =>
      [...jobs].sort((a, b) => normalizeJobSortKey(a).localeCompare(normalizeJobSortKey(b)));

    if (memberProfile) {
      setFullName(memberProfile.memberName || '');
      setMemberId(memberProfile.memberId || '');
      setSelectedJobs(sortJobs(memberProfile.jobFilters || []));
      setCalendarId(memberProfile.calendarId || '');
    }
  }, [memberProfile]);

  useEffect(() => {
    if (session?.user) {
      return;
    }
    const draft = loadDraft();
    if (draft) {
      setFullName(draft.fullName);
      setMemberId(draft.memberId);
      setSelectedJobs(draft.selectedJobs);
    }
    isDraftReadyRef.current = true;
  }, [session?.user]);

  useEffect(() => {
    if (session?.user && memberProfile) {
      clearDraft();
    }
  }, [session?.user, memberProfile]);

  useEffect(() => {
    if (session?.user || !isDraftReadyRef.current) {
      return;
    }
    saveDraft({ fullName, memberId, selectedJobs });
  }, [fullName, memberId, selectedJobs, session?.user]);

  useEffect(() => {
    setCalendarOrigin(window.location.origin);
  }, []);

  useEffect(() => {
    const element = headerRef.current;
    if (!element || typeof ResizeObserver === 'undefined') {
      return;
    }

    const updateHeight = () => {
      setHeaderHeight(element.offsetHeight);
    };

    updateHeight();
    const observer = new ResizeObserver(updateHeight);
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  const requireAuth = () => {
    if (session?.user) {
      return true;
    }
    router.push('/signup?reason=integrations');
    return false;
  };

  const calendarPath = `${CALENDAR_PROXY_PATH}/${calendarId}`;
  const calendarDisplayUrl = calendarOrigin ? `${calendarOrigin}${calendarPath}` : calendarPath;
  const googleCalendarUrl = `https://calendar.google.com/calendar/render?cid=${encodeURIComponent(
    calendarDisplayUrl.replace(/^https:\/\//, 'http://'),
  )}`;
  const outlookCalendarUrl = `https://outlook.live.com/calendar/0/addcalendar?url=${encodeURIComponent(
    calendarDisplayUrl.replace(/^https:\/\//, 'webcal://'),
  )}`;

  const normalizedSearch = jobSearch.trim().toLowerCase();
  const filteredJobOptions = normalizedSearch
    ? SHIFT_JOB_OPTIONS.filter((job) => job.toLowerCase().includes(normalizedSearch))
    : SHIFT_JOB_OPTIONS;

  useEffect(() => {
    if (!isJobDropdownOpen) {
      return;
    }

    if (filteredJobOptions.length === 0) {
      setHighlightedJobIndex(-1);
    } else {
      setHighlightedJobIndex(0);
    }
  }, [filteredJobOptions.length, isJobDropdownOpen]);

  useEffect(() => {
    if (!isJobDropdownOpen || highlightedJobIndex < 0) {
      return;
    }

    const job = filteredJobOptions[highlightedJobIndex];
    const element = job ? jobOptionRefs.current[job] : null;
    element?.scrollIntoView({ block: 'nearest' });
  }, [filteredJobOptions, highlightedJobIndex, isJobDropdownOpen]);

  useEffect(() => {
    if (!isCalendarModalOpen) {
      return;
    }

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setIsCalendarModalOpen(false);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isCalendarModalOpen]);

  const showToast = (variant: ToastVariant, message: string) => {
    const id = Date.now();
    setToasts((previous) => [...previous, { id, variant, message, visible: false }]);

    window.setTimeout(() => {
      setToasts((previous) =>
        previous.map((toast) => (toast.id === id ? { ...toast, visible: true } : toast)),
      );
    }, 10);

    return id;
  };

  const updateToast = (
    id: number,
    updates: Partial<{
      variant: ToastVariant;
      message: string;
      visible: boolean;
    }>,
  ) => {
    setToasts((previous) =>
      previous.map((toast) => (toast.id === id ? { ...toast, ...updates } : toast)),
    );
  };

  const dismissToast = (id: number) => {
    window.setTimeout(() => {
      setToasts((previous) =>
        previous.map((toast) => (toast.id === id ? { ...toast, visible: false } : toast)),
      );
    }, 2500);

    window.setTimeout(() => {
      setToasts((previous) => previous.filter((toast) => toast.id !== id));
    }, 3000);
  };

  const enqueueToast = (variant: ToastVariant, message: string) => {
    const id = showToast(variant, message);
    dismissToast(id);
  };

  const saveJobFilters = async (nextJobs: string[]) => {
    if (!session?.user) {
      return;
    }
    try {
      await updateMemberProfile({ jobFilters: nextJobs });
    } catch (error) {
      enqueueToast(
        'error',
        error instanceof Error ? error.message : 'Failed to update shift filters',
      );
    }
  };

  const toggleJob = (job: string) => {
    setSelectedJobs((previous) => {
      const nextJobs = previous.includes(job)
        ? previous.filter((item) => item !== job)
        : [...previous, job];
      void saveJobFilters(nextJobs);
      return nextJobs;
    });
  };

  const removeJob = (job: string) => {
    setSelectedJobs((previous) => {
      const nextJobs = previous.filter((item) => item !== job);
      void saveJobFilters(nextJobs);
      return nextJobs;
    });
  };

  const handleOpenCalendarModal = () => {
    if (!requireAuth()) {
      return;
    }
    setIsCalendarModalOpen(true);
  };

  const handleCopyCalendarUrl = async () => {
    if (!requireAuth()) {
      return;
    }
    if (!calendarId) {
      enqueueToast('error', 'Create a calendar subscription first.');
      return;
    }

    try {
      await navigator.clipboard.writeText(calendarDisplayUrl);
      enqueueToast('success', 'Copied calendar URL to clipboard.');
    } catch {
      enqueueToast('error', 'Clipboard copy failed. Copy manually from the modal.');
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!requireAuth()) {
      return;
    }
    setIsSaving(true);

    const toastId = showToast('warning', 'Saving profile...');

    try {
      await updateMemberProfile({
        memberName: fullName.trim(),
        memberId: memberId.trim(),
        jobFilters: selectedJobs,
      });
      updateToast(toastId, {
        variant: 'success',
        message: 'Profile successfully updated.',
      });
      dismissToast(toastId);
    } catch (error) {
      updateToast(toastId, {
        variant: 'error',
        message: error instanceof Error ? error.message : 'Failed to save settings',
      });
      dismissToast(toastId);
    } finally {
      setIsSaving(false);
    }
  };

  const handleAddToWallet = async () => {
    if (!requireAuth()) {
      return;
    }
    setIsGeneratingPass(true);
    const toastId = showToast('warning', 'Saving card details...');
    try {
      await updateMemberProfile({
        memberName: fullName.trim(),
        memberId: memberId.trim(),
      });
      updateToast(toastId, {
        variant: 'success',
        message: 'Card details saved. Generating pass...',
      });

      const response = await fetch('/api/wallet/pass');
      if (!response.ok) {
        throw new Error('Failed to generate pass');
      }
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'psfc-member-card.pkpass';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      updateToast(toastId, {
        variant: 'success',
        message: 'Pass downloaded successfully.',
      });
      dismissToast(toastId);
    } catch (error) {
      updateToast(toastId, {
        variant: 'error',
        message: error instanceof Error ? error.message : 'Failed to generate pass',
      });
      dismissToast(toastId);
    } finally {
      setIsGeneratingPass(false);
    }
  };

  const handleAddToGoogleWallet = async () => {
    if (!requireAuth()) {
      return;
    }
    setIsGeneratingGooglePass(true);
    const toastId = showToast('warning', 'Saving card details...');
    try {
      await updateMemberProfile({
        memberName: fullName.trim(),
        memberId: memberId.trim(),
      });
      updateToast(toastId, {
        variant: 'success',
        message: 'Card details saved. Generating pass...',
      });

      const response = await fetch('/api/wallet/google');
      if (!response.ok) {
        throw new Error('Failed to generate pass');
      }
      const { url } = await response.json();
      window.open(url, '_blank');
      updateToast(toastId, {
        variant: 'success',
        message: 'Opening Google Wallet...',
      });
      dismissToast(toastId);
    } catch (error) {
      updateToast(toastId, {
        variant: 'error',
        message: error instanceof Error ? error.message : 'Failed to generate pass',
      });
      dismissToast(toastId);
    } finally {
      setIsGeneratingGooglePass(false);
    }
  };

  if (sessionPending || memberProfile === undefined) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-6">
        <div className="animate-pulse">
          <div className="mb-6 h-8 w-32 rounded bg-zinc-200 dark:bg-zinc-700" />
          <div className="space-y-4">
            <div className="h-10 rounded bg-zinc-200 dark:bg-zinc-700" />
            <div className="h-10 rounded bg-zinc-200 dark:bg-zinc-700" />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      style={
        {
          '--header-offset': `${headerHeight}px`,
        } as CSSProperties
      }
    >
      <div
        ref={headerRef}
        className={`sticky top-24 z-20 bg-white transition-[opacity,transform] duration-300 ease-in-out motion-reduce:transition-none md:top-14 dark:bg-zinc-900 ${
          showSticky ? 'translate-y-0 opacity-100' : 'pointer-events-none -translate-y-2 opacity-0'
        }`}
      >
        <h1 className="mx-auto max-w-3xl px-4 pt-6 pb-6 text-2xl font-bold text-zinc-900 dark:text-zinc-100">
          Integrations
        </h1>
      </div>

      <div
        className="mx-auto max-w-3xl px-4 pb-6 transition-transform duration-300 ease-in-out motion-reduce:transition-none"
        style={{
          transform: showSticky
            ? 'translateY(0px)'
            : 'translateY(calc(-1 * (var(--nav-offset) + var(--header-offset))))',
        }}
      >
        {!session?.user && !sessionPending && (
          <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
            <Link
              href="/signup?reason=integrations"
              className="font-semibold underline underline-offset-4"
            >
              Create an account
            </Link>{' '}
            to save changes, add wallet passes, and subscribe to the shift calendar.
          </div>
        )}

        <form onSubmit={handleSave} className="space-y-6">
          <section className="space-y-4">
            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Profile</h2>
            <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
              Edit your unofficial member card.
            </p>
            <AppleWalletCard
              memberName={fullName}
              memberId={memberId}
              onMemberNameChange={setFullName}
              onMemberIdChange={(value) => setMemberId(value.replace(/\D/g, ''))}
            />
          </section>

          <div className="flex gap-2">
            <button
              type="submit"
              disabled={isSaving}
              className="rounded-lg bg-green-600 px-4 py-1.5 text-sm font-medium text-white transition-colors hover:bg-green-700 disabled:bg-green-400 disabled:opacity-60"
            >
              {isSaving ? 'Saving...' : 'Save'}
            </button>
            <button
              type="button"
              onClick={handleAddToWallet}
              disabled={isGeneratingPass || !memberId || !fullName}
              className="transition-opacity hover:opacity-80 disabled:opacity-40"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/apple-wallet.svg" alt="Add to Apple Wallet" className="h-[34px]" />
            </button>
            <button
              type="button"
              onClick={handleAddToGoogleWallet}
              disabled={isGeneratingGooglePass || !memberId || !fullName}
              className="transition-opacity hover:opacity-80 disabled:opacity-40"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/google-wallet.svg" alt="Add to Google Wallet" className="h-[34px]" />
            </button>
          </div>
        </form>

        <section className="mt-10">
          <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Calendar</h2>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            Link your account to your calendar to view your prospective shifts.
          </p>

          <div className="mt-6 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-700 dark:bg-zinc-900">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h3 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
                  Shift Calendar Syncing
                </h3>
                <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
                  Sync the shift calendar with your Google, Outlook, or Apple calendar.
                </p>
              </div>
              <button
                type="button"
                onClick={handleOpenCalendarModal}
                className="rounded-xl bg-green-600 px-4 py-2 font-medium text-white transition-colors hover:bg-green-700"
              >
                Add iCal subscription
              </button>
            </div>

            <div className="mt-6 space-y-3">
              <div className="space-y-1">
                <h3 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
                  Selected Shifts
                </h3>
                <p className="text-sm text-zinc-600 dark:text-zinc-400">
                  Filter the shift calendar for your preferred shifts.
                </p>
              </div>
              <div className="relative">
                <input
                  type="text"
                  value={jobSearch}
                  onChange={(event) => {
                    setJobSearch(event.target.value);
                    setIsJobDropdownOpen(true);
                  }}
                  onFocus={() => setIsJobDropdownOpen(true)}
                  onBlur={() => {
                    window.setTimeout(() => setIsJobDropdownOpen(false), 150);
                  }}
                  onKeyDown={(event: React.KeyboardEvent<HTMLInputElement>) => {
                    if (event.key === 'ArrowDown') {
                      event.preventDefault();
                      setIsJobDropdownOpen(true);
                      if (filteredJobOptions.length === 0) {
                        return;
                      }
                      setHighlightedJobIndex((previous) =>
                        previous < filteredJobOptions.length - 1 ? previous + 1 : 0,
                      );
                      return;
                    }

                    if (event.key === 'ArrowUp') {
                      event.preventDefault();
                      setIsJobDropdownOpen(true);
                      if (filteredJobOptions.length === 0) {
                        return;
                      }
                      setHighlightedJobIndex((previous) =>
                        previous > 0 ? previous - 1 : filteredJobOptions.length - 1,
                      );
                      return;
                    }

                    if (event.key === 'Enter') {
                      if (!isJobDropdownOpen) {
                        setIsJobDropdownOpen(true);
                        return;
                      }
                      if (filteredJobOptions.length === 0) {
                        return;
                      }
                      event.preventDefault();
                      const job = filteredJobOptions[Math.max(highlightedJobIndex, 0)];
                      if (job) {
                        toggleJob(job);
                      }
                      return;
                    }

                    if (event.key === 'Escape') {
                      setIsJobDropdownOpen(false);
                    }
                  }}
                  placeholder="Search jobs"
                  className="w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm text-zinc-900 shadow-sm focus:ring-2 focus:ring-green-500 focus:outline-none dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-100 dark:focus:ring-green-400"
                />
                {isJobDropdownOpen && (
                  <div className="absolute z-10 mt-2 w-full rounded-xl border border-zinc-200 bg-white shadow-lg dark:border-zinc-700 dark:bg-zinc-900">
                    <div className="max-h-48 overflow-y-auto">
                      {filteredJobOptions.length > 0 ? (
                        filteredJobOptions.map((job, index) => {
                          const isSelected = selectedJobs.includes(job);
                          const isHighlighted = index === highlightedJobIndex;
                          return (
                            <button
                              key={job}
                              ref={(element) => {
                                jobOptionRefs.current[job] = element;
                              }}
                              type="button"
                              onClick={() => toggleJob(job)}
                              onMouseEnter={() => setHighlightedJobIndex(index)}
                              className={`flex w-full items-center justify-between px-3 py-2 text-left text-sm transition-colors ${
                                isSelected
                                  ? 'bg-green-50 text-green-700 dark:bg-green-500/20 dark:text-green-200'
                                  : 'text-zinc-700 hover:bg-zinc-100 dark:text-zinc-200 dark:hover:bg-zinc-800'
                              } ${
                                isHighlighted && !isSelected ? 'bg-zinc-100 dark:bg-zinc-800' : ''
                              }`}
                            >
                              <span>{job}</span>
                              {isSelected && <span className="text-xs">Selected</span>}
                            </button>
                          );
                        })
                      ) : (
                        <div className="px-3 py-2 text-sm text-zinc-500 dark:text-zinc-400">
                          No matching jobs.
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>

              <div className="flex flex-wrap gap-2">
                {selectedJobs.length > 0 ? (
                  selectedJobs.map((job) => (
                    <span
                      key={job}
                      className="group inline-flex items-center gap-2 rounded-full bg-zinc-100 px-3 py-1 text-xs font-medium text-zinc-700 transition-colors hover:bg-red-50 hover:text-red-700 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-red-500/20 dark:hover:text-red-200"
                    >
                      {job}
                      <button
                        type="button"
                        onClick={() => removeJob(job)}
                        className="text-xs font-semibold text-zinc-400 transition-colors group-hover:text-red-600 dark:text-zinc-400 dark:group-hover:text-red-200"
                        aria-label={`Remove ${job}`}
                      >
                        ×
                      </button>
                    </span>
                  ))
                ) : (
                  <span className="text-sm text-zinc-500 dark:text-zinc-400">
                    All shifts included.
                  </span>
                )}
              </div>
            </div>
          </div>
        </section>
      </div>

      {isCalendarModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
          <button
            type="button"
            aria-label="Close calendar modal"
            onClick={() => setIsCalendarModalOpen(false)}
            className="absolute inset-0 bg-black/40"
          />
          <div className="relative w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl dark:bg-zinc-900">
            <div>
              <h3 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100">
                📅 Add iCal subscription
              </h3>
              <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
                Add the shift calendar to your calendar app to keep up with new shifts and updates.
              </p>
            </div>

            <div className="mt-6 space-y-3">
              <a
                href={googleCalendarUrl}
                target="_blank"
                rel="noreferrer"
                className="block w-full rounded-xl bg-[#0b57d0] px-4 py-2 text-center font-medium text-white transition-colors hover:bg-[#0842a0]"
              >
                Add to Google Calendar
              </a>
              <a
                href={outlookCalendarUrl}
                target="_blank"
                rel="noreferrer"
                className="block w-full rounded-xl bg-[#0F6CBD] px-4 py-2 text-center font-medium text-white transition-colors hover:bg-[#0c5a9e]"
              >
                Add to Outlook Calendar
              </a>
              <button
                type="button"
                onClick={handleCopyCalendarUrl}
                disabled={!calendarId}
                className="w-full rounded-xl bg-zinc-100 px-4 py-2 font-medium text-zinc-500 transition-colors hover:text-zinc-700 disabled:opacity-60 disabled:hover:text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400 dark:hover:text-zinc-200 dark:disabled:hover:text-zinc-400"
              >
                Add URL to clipboard
              </button>
            </div>
          </div>
        </div>
      )}

      {toasts.length > 0 && (
        <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 space-y-2">
          {toasts.map((toast) => (
            <div
              key={toast.id}
              className={`rounded-xl border border-zinc-200 bg-white px-4 py-3 text-sm font-medium shadow-lg transition-all duration-300 ease-out dark:border-zinc-700 dark:bg-zinc-900 ${
                toast.visible ? 'translate-y-0 opacity-100' : 'translate-y-2 opacity-0'
              }`}
            >
              <span
                className={
                  toast.variant === 'success'
                    ? 'text-green-600 dark:text-green-400'
                    : toast.variant === 'warning'
                      ? 'text-amber-600 dark:text-amber-400'
                      : 'text-red-600 dark:text-red-400'
                }
              >
                {toast.message}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
