// src/components/produce/ProduceContextMenu.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';
  import { produceItemUrl } from '@/lib/produce-hash';
  import { getSpecialtyProduceUrl } from '@/lib/specialty-produce-map';

  let {
    itemName,
    x,
    y,
    onClose,
  }: {
    itemName: string;
    x: number;
    y: number;
    onClose: () => void;
  } = $props();

  const MENU_GAP = 18;
  const DISMISS_GUARD_MS = 400;

  let copied = $state(false);
  let menuRef = $state<HTMLDivElement | null>(null);
  let openedAt = $state(0);
  let pos = $state<{
    left: number;
    top: number;
    originX: number;
    originY: number;
  } | null>(null);

  const specialtyUrl = $derived(getSpecialtyProduceUrl(itemName));

  async function positionMenu() {
    await tick();
    const menu = menuRef;
    if (!menu) return;
    const { width, height } = menu.getBoundingClientRect();
    const pad = 8;
    let left = x - width / 2;
    let top = y - height - MENU_GAP;
    left = Math.max(pad, Math.min(left, window.innerWidth - width - pad));
    const flipped = top < pad;
    if (flipped) top = y + MENU_GAP;
    const originX = x - left;
    const originY = flipped ? 0 : height;
    pos = { left, top, originX, originY };
  }

  async function handleCopyLink() {
    if (isWithinDismissGuard()) return;
    const url = `${window.location.origin}${produceItemUrl(itemName)}`;
    await navigator.clipboard.writeText(url);
    copied = true;
    setTimeout(() => onClose(), 600);
  }

  function handleSpecialtyLinkClick(event: MouseEvent) {
    if (!isWithinDismissGuard()) return;
    event.preventDefault();
    event.stopPropagation();
  }

  function isWithinDismissGuard(): boolean {
    return Date.now() - openedAt < DISMISS_GUARD_MS;
  }

  function handleBackdropClick(event: MouseEvent) {
    if (isWithinDismissGuard()) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    onClose();
  }

  $effect(() => {
    void positionMenu();
  });

  onMount(() => {
    openedAt = Date.now();

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    const handleClickOutside = (e: MouseEvent | TouchEvent) => {
      if (isWithinDismissGuard()) return;
      if (menuRef && !menuRef.contains(e.target as Node)) {
        onClose();
      }
    };
    const handleScroll = () => {
      if (isWithinDismissGuard()) return;
      onClose();
    };

    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('touchstart', handleClickOutside);
    window.addEventListener('scroll', handleScroll, true);

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('touchstart', handleClickOutside);
      window.removeEventListener('scroll', handleScroll, true);
    };
  });
</script>

<div
  class="fixed inset-0 z-40 bg-black/25 select-none"
  onclick={handleBackdropClick}
  aria-hidden="true"
></div>

<div
  bind:this={menuRef}
  class={`fixed z-50 min-w-[160px] overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-lg ${
    pos ? 'context-menu-genie' : ''
  }`}
  style={
    pos
      ? `left: ${pos.left}px; top: ${pos.top}px; transform-origin: ${pos.originX}px ${pos.originY}px;`
      : `left: ${x}px; top: ${y}px; visibility: hidden;`
  }
>
  {#if specialtyUrl}
    <a
      href={specialtyUrl}
      target="_blank"
      rel="noreferrer"
      onclick={handleSpecialtyLinkClick}
      class="flex w-full items-center gap-3 px-4 py-2.5 text-left text-sm text-zinc-700 transition-colors hover:bg-zinc-100"
    >
      <span>View on Specialty Produce</span>
    </a>
  {:else}
    <div class="px-4 py-2.5 text-sm text-zinc-400">No Specialty Produce link yet</div>
  {/if}

  <button
    type="button"
    onclick={() => {
      void handleCopyLink();
    }}
    class="flex w-full items-center gap-3 px-4 py-2.5 text-left text-sm text-zinc-700 transition-colors hover:bg-zinc-100"
  >
    <span>{copied ? '✅' : '🔗'}</span>
    <span>{copied ? 'Copied!' : 'Copy Link'}</span>
  </button>
</div>

// src/components/ProduceContextMenu.tsx
'use client';

import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { produceItemUrl } from '@/lib/produce-hash';
import { getSpecialtyProduceUrl } from '@/lib/specialty-produce-map';

interface ProduceContextMenuProps {
  itemName: string;
  x: number;
  y: number;
  onClose: () => void;
}

const MENU_GAP = 8;

export function ProduceContextMenu({ itemName, x, y, onClose }: ProduceContextMenuProps) {
  const [copied, setCopied] = useState(false);
  const specialtyUrl = getSpecialtyProduceUrl(itemName);
  const menuRef = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useState<{
    left: number;
    top: number;
    originX: number;
    originY: number;
  } | null>(null);

  useLayoutEffect(() => {
    const menu = menuRef.current;
    if (!menu) return;
    const { width, height } = menu.getBoundingClientRect();
    const pad = 8;
    let left = x - width / 2;
    let top = y - height - MENU_GAP;
    // Clamp to viewport
    left = Math.max(pad, Math.min(left, window.innerWidth - width - pad));
    const flipped = top < pad;
    if (flipped) top = y + MENU_GAP;
    // Transform origin at the touch point relative to the menu
    const originX = x - left;
    const originY = flipped ? 0 : height;
    setPos({ left, top, originX, originY });
  }, [x, y]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    const handleClickOutside = (e: MouseEvent | TouchEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        onClose();
      }
    };
    const handleScroll = () => onClose();

    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('touchstart', handleClickOutside);
    window.addEventListener('scroll', handleScroll, true);
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('touchstart', handleClickOutside);
      window.removeEventListener('scroll', handleScroll, true);
    };
  }, [onClose]);

  const handleCopyLink = async () => {
    const url = `${window.location.origin}${produceItemUrl(itemName)}`;
    await navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => onClose(), 600);
  };

  return (
    <div
      ref={menuRef}
      className={`fixed z-50 min-w-[160px] overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-lg ${pos ? 'context-menu-genie' : ''}`}
      style={
        pos
          ? {
              left: pos.left,
              top: pos.top,
              transformOrigin: `${pos.originX}px ${pos.originY}px`,
            }
          : { left: x, top: y, visibility: 'hidden' as const }
      }
    >
      {specialtyUrl ? (
        <a
          href={specialtyUrl}
          target="_blank"
          rel="noreferrer"
          className="flex w-full items-center gap-3 px-4 py-2.5 text-left text-sm text-zinc-700 transition-colors hover:bg-zinc-100"
        >
          <span>View on Specialty Produce</span>
        </a>
      ) : (
        <div className="px-4 py-2.5 text-sm text-zinc-400">No Specialty Produce link yet</div>
      )}
      <button
        type="button"
        onClick={handleCopyLink}
        className="flex w-full items-center gap-3 px-4 py-2.5 text-left text-sm text-zinc-700 transition-colors hover:bg-zinc-100"
      >
        <span>{copied ? '✅' : '🔗'}</span>
        <span>{copied ? 'Copied!' : 'Copy Link'}</span>
      </button>
    </div>
  );
}
